"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    op.create_table('floor_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), nullable=False),
    sa.Column('image_1', sa.String(length=255), nullable=False),
    sa.Column('image_2', sa.String(length=255)),
    sa.Column('image_3', sa.String(length=255)),
    sa.Column('image_4', sa.String(length=255)),
    sa.Column('image_5', sa.String(length=255)),
    sa.Column('image_6', sa.String(length=255)),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('date_available', sa.Date(), nullable=False),
    sa.Column('floor_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id']),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    op.drop_table('floor_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
